export const projects = [
  {
    code: 1,
    title: "Projeto A",
    description: "Projeto de Calculadora",
    tecnologies: ["Vue.js"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 2,
    title: "Projeto B",
    description: "Projeto de Cronometro",
    tecnologies: ["React.js"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 3,
    title: "Projeto C",
    description: "Projeto de Calendário",
    tecnologies: ["React.js"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 4,
    title: "Projeto D",
    description: "Projeto de Mercadinho",
    tecnologies: ["HTML", "CSS", "JavaScript"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 5,
    title: "Projeto E",
    description: "Projeto medo de todo programadores",
    tecnologies: ["Java"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 6,
    title: "Projeto F",
    description: "Projeto Mercadinho com Back-end",
    tecnologies: ["HTML", "CSS", "JavaScript", "Node.js"],
    repository_link: "",
    aplication_link: "",
  },
  {
    code: 7,
    title: "Projeto G",
    description: "Site de instituição infantil",
    tecnologies: ["HTML", "CSS"],
    repository_link: "",
    aplication_link: "",
  },
]